name: Create Release on Tag

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create zip archive
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: 'zip'
          filename: '${{ github.event.repository.name }}-${{ github.ref_name }}.zip'
          exclusions: '*.git* /*node_modules/* .editorconfig .vscode .vscode/* README.md LICENSE'
          directory: '.'
          path: 'src'

      - name: Publish Release with Release Drafter
        id: release_drafter
        uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter.yml
          publish: true
          tag: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release_drafter.outputs.upload_url }}
          asset_path: ./${{ github.event.repository.name }}-${{ github.ref_name }}.zip
          asset_name: ${{ github.event.repository.name }}-${{ github.ref_name }}.zip
          asset_content_type: application/zip
