name: Create Release on Tag

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create zip archive
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: 'zip'
          filename: '${{ github.event.repository.name }}-${{ github.ref_name }}.zip'
          exclusions: '*.git* /*node_modules/* .editorconfig .vscode .vscode/* README.md LICENSE'
          directory: '.'
          path: 'src'

      - name: Publish Release
        uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter.yml
          publish: true
          tag: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Release Upload URL
        id: get_release
        run: |
          UPLOAD_URL=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ github.ref_name }}" | \
            jq -r .upload_url)
          echo "upload_url=$UPLOAD_URL" >> "$GITHUB_OUTPUT"

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./${{ github.event.repository.name }}-${{ github.ref_name }}.zip
          asset_name: ${{ github.event.repository.name }}-${{ github.ref_name }}.zip
          asset_content_type: application/zip
